### ISSUE TITLE
Style transfer does not occur when using default configurations

### ISSUE THREAD

**Issue by Tonniia** [liujin112/PortraitDiffusion#1]
Hi, when I use default configurations along with the style and content images provided, the results don't seem to effectively transfer the style:
![image](https://github.com/liujin112/PortraitDiffusion/assets/56153611/342bce35-a76d-4f70-b153-a69cf8a66b10)
Is there any configuration I need to change? Thanks

**Comment by liujin112** [comment]
@Sutongtong233 We've updated default configurations so you can try it again. We highly recommend using the Gradio app, provides an easier way to modify configurations and may help you figure out where the problem is.

**Comment by Tonniia** [comment]
Thanks a lot!
