### ISSUE TITLE
由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

### ISSUE THREAD

**Issue by happypuppy128** [liujin112/PortraitDiffusion#2]
<img width="1259" alt="屏幕截图 2023-12-19 212514" src="https://github.com/liujin112/PortraitDiffusion/assets/136563273/c2bb4101-acd4-4bd7-b084-2dcdb8284612">
大佬，这是什么情况，an按照你的提示安装好了依赖项为什么还是会报错

**Comment by happypuppy128** [comment]
还在下载什么东西吗

**Comment by liujin112** [comment]
模型权重文件会自动从 huggingface 下载，需要确保你的网络能够正常访问 huggingface.com。或者你也可以尝试下载模型文件到本地，修改代码从本地加载模型。

**Comment by happypuppy128** [comment]
> 模型权重文件会自动从 huggingface 下载，需要确保你的网络能够正常访问 huggingface.com。或者你也可以尝试下载模型文件到本地，修改代码从本地加载模型。

那么需要哪些模型呢，我看你huggingface的file目录只有一个Lora里面有一个add的风格模型？
