### ISSUE TITLE
请问需要哪些模型文件

### ISSUE THREAD

**Issue by happypuppy128** [liujin112/PortraitDiffusion#3]
我有去huggingface看到你的实例，加载包含了sdv-1.5的模型和一个add_details的一个Lora模型，但是很奇怪的是我去查看目录，仅有一个Lora模型，所以我有点懵

**Comment by liujin112** [comment]
Base 模型是从 Huggingface 自动下载的

**Comment by liujin112** [comment]
@qwertyuiopasdfhgjkbwrhbioveev  Base 模型是从 Huggingface 自动下载的。具体请参考 [Load pipelines, models, and schedulers](https://huggingface.co/docs/diffusers/using-diffusers/loading)

**Comment by happypuppy128** [comment]
> @qwertyuiopasdfhgjkbwrhbioveev Base 模型是从 Huggingface 自动下载的。具体请参考 [Load pipelines, models, and schedulers](https://huggingface.co/docs/diffusers/using-diffusers/loading)

是的，正常来说会比较方便，但是因为国内的缘故，huggingface下载这些模型反而不是那么方便，如果能在国内的比如摩达社区这种部署是不是可能会更好一点点，huggingface上部署的我也看不出还有哪些别的文件，比如分词器token....？最近你还在研究类似方面吗，我们或许可以换个地方交流一下

**Comment by liujin112** [comment]
@qwertyuiopasdfhgjkbwrhbioveev 摩达社区提供了下载模型的API，可以先使用他们的 API 下载模型，再使用 Diffusers 加载，例如[lcm-sdxl · 模型库](https://modelscope.cn/models/AI-ModelScope/lcm-sdxl/summary)。如果需要进一步交流欢迎给我发邮件。

**Comment by happypuppy128** [comment]
> @qwertyuiopasdfhgjkbwrhbioveev 摩达社区提供了下载模型的API，可以先使用他们的 API 下载模型，再使用 Diffusers 加载，例如[lcm-sdxl · 模型库](https://modelscope.cn/models/AI-ModelScope/lcm-sdxl/summary)。如果需要进一步交流欢迎给我发邮件。

我很荣幸我正在研究的是你的硕士学位项目，如果您能抽空给出一些必要的模型的目录，我想这会让你的项目能更加易于引用和学习，仅个人看法，很感谢你的耐心回答，祝您的项目star多多

**Comment by liujin112** [comment]
需要使用的模型只有 SD v1.5 一个，LoRA 模型只是提供了个性化的选项，可以不使用。你可能需要了解一下如何使用 Diffusers 加载 SD v1.5。

**Comment by happypuppy128** [comment]
> 需要使用的模型只有 SD v1.5 一个，LoRA 模型只是提供了个性化的选项，可以不使用。你可能需要了解一下如何使用 Diffusers 加载 SD v1.5。

<img width="1256" alt="屏幕截图 2023-12-21 193623" src="https://github.com/liujin112/PortraitDiffusion/assets/136563273/d3a81b68-0f92-4c9a-a052-cfe09185b042">
您知道正确的这个模型吗，应该是diffusion_pytorch_model.bin这个模型文件的问题，但是我分别在huggingface下载的和摩达社区下载了这个模型文件，依旧会有这个错误对于这个文件diffusion_pytorch_model.bin对应有两个大小在unet下面的3.44GB大小和vae下面的335MB的，如果您方便，能解答一下吗

**Comment by happypuppy128** [comment]
> 需要使用的模型只有 SD v1.5 一个，LoRA 模型只是提供了个性化的选项，可以不使用。你可能需要了解一下如何使用 Diffusers 加载 SD v1.5。

这个两个我都试了，都有类似的错误

**Comment by liujin112** [comment]
这两个文件都只是整个 SD v1.5 的一个模块，你只加载一个当然会报错😂。
